jobs:
  build:
    docker:
      - image: circleci/node:14.16.1
    steps:
      - checkout
      - run: sudo apt update
      - run: npm install
      - run: npm run build
      - run: npm run test 
      
