jobs:
  build:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: export PATH=~/.local/bin:$PATH
        # Download and cache dependencies
      - run: sudo apt-get update
      - run: sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - run: npm install
      - run: npm run build
      - run: npx next telemetry --disable
      - run: npm run lint:fix
      - run: npm run test