jobs:
  build:
    docker:
      - image: circleci/node:14.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: export PATH=~/.local/bin:$PATH
      - run: sudo apt update
      - run: npm install
      - run: npm run build
      - run: npm run test 
      - run: npm run forceExit
      
