jobs:
  build:
    docker:
      - image: circleci/node:14.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get update
      - run: npm install
      - run: npm run build
      - run: npm run test
      

